import { useState } from "react";
import Avatar from "../assets/images/avatar.jpg";

//! please write a document for this data structure
const useLotteryCreateData = () => {
  const [lotteryCreateList, setLotteryCreateList] = useState([
    {
      disabled: false,
      title: "حالت قرعه کشی",
      description: "",
      token: "fsgxvxcvdfsxcvxfgdhfgggjgjf",
      hasSwitch: false,
      label: "lotteryMode",
      type: "list",
      list: [
        {
          disabled: false,
          title: "قرعه کشی لایک",
          token: "gdfg34tertgd",
          mode: "like",
          hasSwitch: true,
          checked: false,
        },
        {
          disabled: false,
          title: "قرعه کشی کامنت",
          token: "gdfg34tdfsvxertgd",
          mode: "comment",
          hasSwitch: true,
          checked: true,
        },
      ],
    },
    // {
    //   disabled: false,
    //   title: "شرکت کننده ها",
    //   description: "",
    //   hasSwitch: false,
    //   select: true,
    //   token: "fsgxvxcvfgdhfgggjgjf",
    //   type: "list",
    //   list: [
    //     {
    //       disabled: false,
    //       title: "همه",
    //       token: "gdfg34dfsvxvrtgd",
    //       enabled: true,
    //     },
    //     {
    //       disabled: false,
    //       title: "انتخاب",
    //       token: "gdfgbcctertgd",
    //       enabled: false,
    //     },
    //   ],
    //   selectList: [
    //     {
    //       username: "mmdzov",
    //       image: Avatar,
    //       userId: 1324257556,
    //       token: "gdrteppd4sadcxzsdpfskp",
    //       selected: false,
    //     },
    //     {
    //       username: "mmdzov",
    //       image: Avatar,
    //       userId: 1324457556,
    //       token: "gdrteghfgdfsdfvxcfsdpfskp",
    //       selected: true,
    //     },
    //   ],
    // },
    {
      disabled: false,
      title: "شروط قرعه کشی",
      description: "",
      hasSwitch: false,
      token: "fsgxvxcvfgfsdfxvdhfgggjgjf",
      label: "conditionList",
      type: "conditionList",
      list: [
        {
          disabled: false,
          title: "شرط اول",
          text: "توضیحات شرط اول",
          token: "gdfg34tefdassvxcvrtgd",
        },
        {
          disabled: false,
          title: "شرط دوم",
          text: "توضیحات شرط دوم",
          token: "gdfg34tfsdvxcvxtgd",
        },
      ],
    },
    {
      disabled: false,
      title: "نمایش همگانی شرکت کنندگان",
      description: "",
      token: "fsgxvxfsxcvcvfgdhfgggjgjf",
      hasSwitch: true,
      label: "showAllUsers",
      checked: true,
      type: "switch",
    },
    {
      disabled: false,
      title: "حداقل/حداکثر شرکت کننده (نفر)",
      description: "",
      token: "fsgxfxvcxcvxcvfgdhfgggjgjf",
      hasSwitch: false,
      type: "inputList",
      list: [
        {
          disabled: false,
          title: "حداقل",
          type: "number",
          placeholder: "تعداد",
          name: "minUsers",
          value: 1,
          token: "fxvcchr54ergd",
        },
        {
          disabled: false,
          title: "حداکثر",
          type: "number",
          placeholder: "تعداد",
          name: "maxUsers",
          value: -1,
          token: "tergdu67tfghf",
        },
      ],
    },
    {
      disabled: false,
      title: "تعداد برنده ها",
      description: "",
      token: "fsgxgfdgccvxcvfgdhfgggjgjf",
      hasSwitch: false,
      type: "inputNumber",
      name: "winnersCount",
      value: 10,
      placeholder: "تعداد",
    },
    {
      disabled: false,
      title: "نحوه قرعه کشی",
      token: "fsgxgfdgghfbcvgdhfgggjgjf",
      description:
        "در حالت خودکار, یک زمان مشخص میکنید برای شروع قرعه کشی و زمان قرعه کشی",
      hasSwitch: false,
      label: "howLottery",
      type: "list",
      list: [
        {
          disabled: false,
          title: "فشردن دکمه",
          token: "gdfdfsdfg34tertgd",
          hasSwitch: true,
          mode: "pressBtn",
          checked: true,
        },
        {
          disabled: false,
          title: "تکان دادن موبایل",
          token: "gdfg3fsvxtdfsvxertgd",
          mode: "shakeMobile",
          hasSwitch: true,
          checked: false,
        },
        {
          disabled: false,
          title: "خودکار",
          token: "gdfg3fvxvvdfsvxertgd",
          mode: "auto",
          hasSwitch: true,
          checked: false,
        },
      ],
    },
    {
      disabled: false,
      title: "دفعات قرعه کشی",
      description:
        "می توانید انتخاب کنید که با هر بار لمس یا تکان دادن گوشی خود, بصورت تکی یک کاربر انتخاب شود یا همگی افراد بر اساس تعداد برندگان انتخاب شود",
      hasSwitch: false,
      token: "fsgxgfdgghfbadsdafgggjgjf",
      label: "lotteryCount",
      type: "list",
      list: [
        {
          disabled: false,
          title: "فردی",
          token: "gdfvxvcfg34tertgd",
          hasSwitch: true,
          mode: "single",
          checked: true,
        },
        {
          disabled: false,
          title: "همگانی",
          token: "gdfgfsvxcxtdfsvxertgd",
          mode: "all",
          hasSwitch: true,
          checked: false,
        },
      ],
    },
    {
      disabled: false,
      title: "اعلام برد به برنده ها",
      description:
        "ارسال پیغام به دایرکت برنده های قرعه کشی, میتوانید از تگ های پایین برای نام کاربر / کد قرعه کشی کاربر و آیدی عددی کاربر استفاده کنید. بظور مثال اگر بخواهید از نام کاربر در پیغام سفارشی تان استفاده کنید میتوانید بر روی username لمس کنید",
      hasSwitch: false,
      // checked: false,
      type: "messageToWinners",
      label: "messageToWinners",
      name: "msgToWinners",
      value: "",
      placeholder: "متن پیشفرض...",
      tagList: [
        {
          disabled: false,
          title: "username",
          token: "gdfvxvcfg34tertgd",
          hasSwitch: false,
        },
        {
          disabled: false,
          title: "code",
          token: "gdfgfsfvcxvctgd",
          hasSwitch: false,
        },
        {
          disabled: false,
          title: "userId",
          token: "gdfgfsvfgdffsvxertgd",
          hasSwitch: false,
        },
      ],
    },
    // {
    //   disabled: false,
    //   title: "بر اساس",
    //   description:
    //     "می توانید بر اساس تعداد لایک کامنت/کامنت یک رسانه , به کاربران اجازه بدهید در قرعه کشی شرکت کنند مثال: اگر شما تعدادی را وارد کنید ",
    //   hasSwitch: false,
    //   type: "inputNumber",
    //   placeholder: "تعداد",
    //   name: "basedOnCount",
    //   value: "",
    // },
    {
      disabled: false,
      title: "شرط های ویژه قرعه کشی",
      description:
        "می توانید برای ورود افراد به قرعه کشی , شرط های ویژه اینستاتو را اعمال کنید",
      hasSwitch: false,
      type: "collapse",
      token: "terfsdfsadzudfsdv67tfghf",
      collapseList: [
        {
          disabled: false,
          title: "انتخاب رسانه",
          type: "text",
          description:
            "می توانید یک یا چند رسانه را برای اجرای شروط ویژه انتخاب کنید. اگر می خواهید تغییرات تنها بر روی رسانه فعلی اعمال شود نیاز به پر کردن این فیلد نمی باشد",
          placeholder: "پیوند رسانه...",
          name: "selectMultipleMedia",
          label: "selectMultipleMedia",
          value: "",
          token: "tergdsadzudfsdv67tfghf",
          mediaList: [
            {
              url: "https://instagram/mmdzov/tv/dfsDSfd32",
              token: "gkpfopdsk43sadxzxcz",
            },
            {
              url: "https://instagram/mmdzov/tv/dfsDSfd32",
              token: "gkhjkopdsk43sadxzxcz",
            },
            {
              url: "https://instagram/mmdzov/tv/dfsDSfd32",
              token: "gjghjbpdsk43sadxzxcz",
            },
          ],
        },
        {
          disabled: false,
          title: "تعداد کامنت",
          type: "number",
          description:
            "میتوانید مشخص کنید که شرکت کننده باید چند کامنت گذاشته باشد تا بتواند شرکت کند",
          placeholder: "تعداد",
          name: "condAllowCommentCount",
          label: "condAllowCommentCount",
          value: -1,
          token: "tergdudfsdv67tfghf",
        },
        {
          disabled: false,
          title: "تعداد لایک",
          type: "number",
          description:
            "میتوانید مشخص کنید که شرکت کننده باید چند لایک گذاشته باشد تا بتواند شرکت کند",
          placeholder: "تعداد",
          name: "condAllowLikeCount",
          label: "condAllowLikeCount",
          value: -1,
          token: "tergdudvxcvxcxfdsdv67tfghf",
        },
        {
          disabled: false,
          title: "تعداد گذاشتن لایک کامنت",
          type: "number",
          description:
            "میتوانید مشخص کنید که شرکت کننده باید حداقل چند لایک کامنت گذاشته باشد تا بتواند شرکت کند",
          placeholder: "تعداد",
          name: "condAllowPutLikeCount",
          label: "condAllowPutLikeCount",
          value: -1,
          token: "tergdudfsdadsdfsfdsdv67tfghf",
        },
        {
          disabled: false,
          title: "تعداد داشتن لایک کامنت",
          type: "number",
          description:
            "میتوانید مشخص کنید که شرکت کننده باید حداقل چند لایک کامنت داشته باشد تا بتواند شرکت کند",
          placeholder: "تعداد",
          name: "condAllowHaveLikeCount",
          label: "condAllowHaveLikeCount",
          value: -1,
          token: "tergdufsdfsvafdsdv67tfghf",
        },
        {
          disabled: false,
          title: "تعداد گذاشتن ریپلای کامنت",
          type: "number",
          description:
            "میتوانید مشخص کنید که شرکت کننده باید حداقل چند لایک کامنت گذاشتن باشد تا بتواند شرکت کند",
          placeholder: "تعداد",
          name: "condAllowPutReplyCount",
          label: "condAllowPutReplyCount",
          value: -1,
          token: "tergduvxsdasddsdv67tfghf",
        },
        {
          disabled: false,
          title: "تعداد داشتن ریپلای کامنت",
          type: "number",
          description:
            "میتوانید مشخص کنید که شرکت کننده باید حداقل چند لایک کامنت داشته باشد تا بتواند شرکت کند",
          placeholder: "تعداد",
          name: "condAllowHaveReplyCount",
          label: "condAllowHaveReplyCount",
          value: -1,
          token: "tergduvxcvafdsdv67tfghf",
        },
        {
          disabled: false,
          title: "فالو کردن پیج درج شده",
          name: "condFollowThisPage",
          label: "condFollowThisPage",
          token: "terfsdfsvcuvhgfgafdsdv67tfghf",
          hasSwitch: true,
          checked: true,
          type: "switch",
        },
        {
          disabled: false,
          title: "اجباری کردن مشاهده استوری ها",
          description:
            "اگر این دکمه فعال باشد کاربر برای پیروی از قوانین قرعه کشی می بایست تمام استوری های پیچ درج شده را زمان فرا رسیدن قرعه کشی مشاهده کند",
          name: "condViewAllStories",
          label: "condViewAllStories",
          token: "tergduvhgfgafdsdv67tfghf",
          hasSwitch: true,
          label: "condViewAllStories",
          checked: false,
          type: "switch",
        },
        {
          disabled: false,
          title: "دنبال کردن تمام فالووینگای پیج درج شده",
          description:
            "شرکت کننده باید تمام دنبال کنندگان پیج درج شده را دنبال کند",
          placeholder: "تعداد",
          name: "condFollowAllFollowings",
          label: "condFollowAllFollowings",
          token: "tergdasdaxcvafdsdv67tfghf",
          label: "condFollowAllFollowings",
          hasSwitch: true,
          checked: false,
          type: "switch",
        },
        {
          disabled: false,
          title: "لایک کردن اخرین رسانه های دنبال کنندگان",
          description:
            "شرکت کننده موظف است اخرین رسانه های دنبال کنندگان پیج درج شده را لایک کند",
          placeholder: "تعداد",
          name: "condLikeLastMediaFollowings",
          label: "condLikeLastMediaFollowings",
          token: "tergdasdaxcvafsdfstfghf",
          label: "condLikeLastMediaFollowings",
          hasSwitch: true,
          checked: false,
          type: "switch",
        },
        {
          disabled: false,
          title: "لایک کردن تمام رسانه های دنبال کنندگان",
          description:
            "شرکت کننده موظف است تمام رسانه های دنبال کنندگان پیج درج شده را لایک کند",
          placeholder: "تعداد",
          name: "condLikeAllMediaFollowings",
          label: "condLikeAllMediaFollowings",
          token: "tergdasdadasczxdv67tfghf",
          label: "condLikeAllMediaFollowings",
          hasSwitch: true,
          checked: false,
          type: "switch",
        },
        {
          disabled: false,
          title: "کامنت گذاشتن در آخرین رسانه های دنبال کنندگان",
          description:
            "شرکت کننده موظف است در آخرین رسانه های دنبال کنندگان پیج درج شده کامنت بگذارد",
          placeholder: "تعداد",
          name: "condCommentLastMediaFollowings",
          label: "condCommentLastMediaFollowings",
          token: "tergdasddasdadsdv67tfghf",
          label: "condCommentLastMediaFollowings",
          hasSwitch: true,
          checked: false,
          type: "switch",
        },
        {
          disabled: false,
          title: "کامنت گذاشتن در تمام رسانه های دنبال کنندگان",
          description:
            "شرکت کننده موظف است در تمام رسانه های دنبال کنندگان پیج درج شده کامنت بگذارد",
          placeholder: "تعداد",
          name: "condCommentAllMediaFollowings",
          label: "condCommentAllMediaFollowings",
          token: "tergdhfgdbvafdsdv67tfghf",
          label: "condCommentAllMediaFollowings",
          hasSwitch: true,
          checked: false,
          type: "switch",
        },
      ],
    },
  ]);
  return [lotteryCreateList, setLotteryCreateList];
};
//! please write a document for this data structure
export default useLotteryCreateData;
